require("awful.autofocus")
require("modules/theme")
require("modules/utils")
require("modules/screens")
require("modules/signals")
require("modules/notifications")
require("modules/rules")
require("modules/autostart")